import "dotenv/config";
import { defineConfig, env } from "prisma/config";

/**
 * Generated by `prisma init`, then configured for this portfolio.
 * CLI migrate/status uses DIRECT_URL (session pooler).
 * App runtime still uses DATABASE_URL from schema.prisma (transaction pooler).
 * @see https://www.prisma.io/docs/orm/reference/prisma-config-reference
 */
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: env("DIRECT_URL"),
  },
});
